feat: pray DAO DTO / storage DAO DTO
PrayHelper/prayhelper-backend pull request #22
Opened 2023-04-12 04:50 UTC by 200516bb

2023-04-13 01:00 UTC, baebae02 requested changes
DTO&DAO는 어느정도 끝났고 피드백 반영 후 CRUD API만들면 될 것 같아요 TODO에 추가해서 적어둘게용 이 브랜치 그대로 갑시다 ~~!

2023-04-13 01:00 UTC, baebae02 commented on app/api/pray.py
> +
안쓰는건 주석 처리 말고 삭제해도 좋아요 🙌🏻

2023-04-13 01:00 UTC, baebae02 commented on app/utils/pray.py
> +        self.created_at = created_at
created_at을 nullable=False, default=datetime.datetime.now()로 바꾼 후 StorageDTO에서 지워봅시다. 입력 안받아도 되게끔 !
pray_cnt도 마찬가지로 입력받는 것이 아닌 default=0으로 들어가게끔 StorageDTO에서 없애봅시다 :)

2023-04-13 01:00 UTC, baebae02 commented on app/utils/pray.py
> +            self = storage
이것도 바꿔야겠네` self.id = storage.id`

2023-04-13 01:00 UTC, baebae02 commented on app/api/pray.py
> +		Pray Post
동사를 먼저 쓰는게 좋을 것 같아요 Post pray 아니면 한글로 "기도제목 입력하기" 도 좋을 것 같아요오

2023-04-17 16:05 UTC, 200516bb commented on app/models/pray.py
> +		pray = db.relationship('Pray', backref=db.backref('pray', lazy=True))
lazy가 먼지 몰라서 찾아봤는데 기본옵션이 lazy=true라던데 써놓은 이유가 있나욥??

2023-04-17 16:05 UTC, 200516bb commented on app/utils/pray.py
> +    id: Union[id, None]
id라는 타입도 있는곤가요??

2023-04-17 16:05 UTC, 200516bb commented on app/utils/pray.py
> +    def __repr__(self):
이건 무슨 역할을 하는 함수인가요?!

2023-04-17 16:05 UTC, 200516bb commented on app/utils/pray.py
> +    created_at: Union[dataclass, None] = None
이건 datetime말고 dataclass로 하는 이유가먼가요??

2023-04-17 16:05 UTC, 200516bb commented on app/utils/pray.py
> +    def get_storages() -> List[StorageDTO]:
엇 이게 storage json 형태로 반환해주는 함수인가요??

2023-04-17 16:21 UTC, 200516bb commented on app/utils/pray.py
> +        self.created_at = created_at
이거 지금... 고치고있는데용 새로 커밋해준 코드에 싹다 created_at이랑 pray_cnt가 들어가있는데 얘네 지워도 되는건가요..?! repr 이 함수에도 들어가있고 지워도되나 싶어성

2023-04-17 16:24 UTC, 200516bb commented on app/api/pray.py
> +		기도제목을 입력합니다.
이거 입력이아니라 갖고오는거죠??!

2023-04-17 23:42 UTC, baebae02 commented on app/utils/pray.py
> +        self.created_at = created_at
아 맞아 내가 PR해놓고 ... 코드를 바꿔가지고 ㅠㅠㅠㅠ 죄송함다 __repr__에 cnt랑  created_at을 넣으려면  init에도 포함이 되어야 하더라구요 .... 없으면 `self.created_at`이 안되가지구 넣는걸로 합시다 😭😭

2023-04-17 23:43 UTC, baebae02 commented on app/models/pray.py
> +		pray = db.relationship('Pray', backref=db.backref('pray', lazy=True))
어머 이게 기본 설정이구나 난로딩속도 개선인줄만 알았지 기본인줄 몰랐어용 고마워요 !!! 빼줍시다 !!!!!! 수빈짱짱맨 !!!!

2023-04-17 23:44 UTC, baebae02 commented on app/utils/pray.py
> +    def __repr__(self):
파이썬에서 __init__이 초기화 (시작세팅)을 뜻한다면 얘는 print찍었을때 나오는 포맷을 미리 지정해둔겁니다 ! 원래 print(StorageDTO)를 했다면 <StorageDTO>가 나오지만 이젠 __repr__가 있어서 저 형식대로 출력되는거죵 ㅎㅎㅎ

2023-04-17 23:45 UTC, baebae02 commented on app/utils/pray.py
> +    created_at: Union[dataclass, None] = None
datetime...은 자료형이아니더군요 ㅠ 저기에 datetime넣으니까 에러나요 흑흑 import datetime하는 걸 보아 datetime은 라이브러리인듯 !

2023-04-17 23:46 UTC, baebae02 commented on app/utils/pray.py
> +    def get_storages() -> List[StorageDTO]:
넹 맞아용 ! 지금 입력값은 아무것도 없고 출력값은 List[StorageDTO] 형식대로 return하는 함수입니다 ! 밑에 코드도 이제 storage불러와서 .. __repr__로 뱉어주는 .. !

2023-04-17 23:46 UTC, baebae02 commented on app/api/pray.py
> +		기도제목을 입력합니다.
어머 주석 에러입니다 감사합니다 ㅠㅠㅠㅠ 기도제목을 조회합니다 로 바꾸면 될 것 같아용 ㅠㅠ

2023-04-30 12:05 UTC, baebae02 commented on app/api/pray.py
> +		return StorageService.update_storage(pray_id, content['pray_cnt'], content['deadline']), 200
이렇게 하면 pray_cnt만 늘리거나 deadline만 변경할 수 없어요 !무조건 두개 다보내야 하는 거라 둘중 하나만 보내도 되게끔 코드를 수정해야합니당 제가 수정해서 올릴테니 다음번에 참고해주세여 ~~

2023-04-30 12:09 UTC, baebae02 approved these changes

2023-04-30 12:16 UTC, 200516bb commented on app/api/pray.py
> +		return StorageService.update_storage(pray_id, content['pray_cnt'], content['deadline']), 200
헐 천잰가..이렇게 바꾸면되는구나
알겠습니다!!

2023-04-30 12:21 UTC, merged

2023-04-30 12:21 UTC, baebae02 commented
@200516bb 머지했어용 ~~ pray & storage는 여기서 마무리하겠슴다 🙆🏻‍♀️